# Generated by Django 5.2.5 on 2025-09-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ataque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dano', models.IntegerField(default=0)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('efeito', models.TextField()),
                ('bonus_vida', models.IntegerField(default=0)),
                ('bonus_forca', models.IntegerField(default=0)),
                ('malus_defesa', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bonus_forca', models.IntegerField(default=0)),
                ('bonus_defesa', models.IntegerField(default=0)),
                ('bonus_agilidade', models.IntegerField(default=0)),
                ('bonus_magia', models.IntegerField(default=0)),
                ('bonus_vida', models.IntegerField(default=0)),
                ('preco', models.IntegerField(default=0)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(default=1)),
                ('vida', models.IntegerField(default=40)),
                ('forca', models.IntegerField(default=5)),
                ('defesa', models.IntegerField(default=5)),
                ('velocidade', models.IntegerField(default=10)),
                ('magia', models.IntegerField(default=5)),
            ],
        ),
    ]
