# Generated by Django 5.2.5 on 2025-09-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inimigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(default=1)),
                ('vida', models.IntegerField(default=40)),
                ('forca', models.IntegerField(default=5)),
                ('defesa', models.IntegerField(default=5)),
                ('velocidade', models.IntegerField(default=10)),
                ('magia', models.IntegerField(default=5)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
